✨ Export of joined entities
DataSentics/odap pull request #14
Opened 2022-11-03 22:33 UTC by KubaVaclavik

- Added joining multiple featurestores to segment
- Added logging to segment-factory

2022-11-04 13:36 UTC, guderkar requested changes

2022-11-04 13:36 UTC, guderkar commented on src/odap/common/databricks.py
> +    dbutils = resolve_dbutils()
?

2022-11-04 13:36 UTC, guderkar commented on src/odap/common/databricks.py
> +def get_host() -> str:
Why do we put workspace url to config?

2022-11-07 08:44 UTC, KubaVaclavik commented on src/odap/common/databricks.py
> +def get_host() -> str:
`spark.databricks.workspaceUrl ` is pre-set config. So we don't have to set it up. 

I changed it because `.getDbutils().notebook().getContext().browserHostName().get()` is failing in job run

2022-11-07 12:56 UTC, guderkar approved these changes

2022-11-07 13:01 UTC, merged