:sparkles: Added option to toggle features df display
DataSentics/odap pull request #22
Opened 2022-11-10 13:47 UTC by Vinsho

- Display takes quite a long time, so display it only if user wants it

2022-11-10 14:35 UTC, guderkar requested changes

2022-11-10 14:46 UTC, Vinsho commented on src/odap/feature_factory/dry_run.py
> +def dry_run(display_features=False):
Hmm, it felt like too much for a display functionality. :thinking:

2022-11-10 15:24 UTC, guderkar commented on src/odap/feature_factory/dry_run.py
> +def dry_run(display_features=False):
yes but if its like argument user would have to change dry run notebook code

2022-11-11 08:51 UTC, guderkar approved these changes

2022-11-11 09:20 UTC, merged