feat: added usecase generator
DataSentics/odap pull request #44
Opened 2022-12-16 10:42 UTC by fkrjakDatasentics

Use case generator for table added 

Example notebook https://adb-8406481409439422.2.azuredatabricks.net/?o=8406481409439422#notebook/1872984241537364/command/3964698646820817

2022-12-19 11:57 UTC, ds-lukaslangr requested changes

2022-12-19 11:57 UTC, ds-lukaslangr commented on src/odap/use_case/generate.py
> +    path = get_config_namespace(ConfigNamespace.USECASE_FACTORY)["path"]
shouldn't this be called `table_name` instead?

2022-12-19 11:57 UTC, ds-lukaslangr commented on src/odap/use_case/generate.py
> +    try:
you probably shouldn't use try except for control flow
this whole thing could be handled using [delta merge](https://docs.delta.io/latest/delta-update.html#merge-examples) where `name` is the primary key of the use case table

or why not just overwrite the table everytime?

2022-12-19 11:57 UTC, ds-lukaslangr commented on src/odap/use_case/notebooks.py
> +    if segments:
switch this around so it's `if not segments`

2022-12-20 13:05 UTC, fkrjakDatasentics commented on src/odap/use_case/generate.py
> +    path = get_config_namespace(ConfigNamespace.USECASE_FACTORY)["path"]
Sounds better than my name, changing it

2022-12-20 13:11 UTC, fkrjakDatasentics commented on src/odap/use_case/generate.py
> +    try:
True

2023-01-05 14:18 UTC, ds-lukaslangr approved these changes

2023-01-16 15:56 UTC, closed without merging