:art: Added pre orchestration tables validation
DataSentics/odap pull request #47
Opened 2022-12-20 07:57 UTC by guderkar

2022-12-20 08:51 UTC, ds-lukaslangr requested changes

2022-12-20 08:51 UTC, ds-lukaslangr commented on src/odap/common/tables.py
>      spark = SparkSession.getActiveSession()  # pylint: disable=W0641
change disable to error name

2022-12-20 08:51 UTC, ds-lukaslangr commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
can we catch the correct Exception?

2022-12-20 08:51 UTC, ds-lukaslangr commented on src/odap/feature_factory/tables_validator.py
> +        raise Exception(f"Table '{full_table_name}' exists in Databricks Feature Store but not in hive")
maybe use FileNotFoundError?

2022-12-20 08:51 UTC, ds-lukaslangr commented on src/odap/feature_factory/tables_validator.py
> +        raise Exception(f"Table '{full_table_name}' exists in hive but not in path '{path}'")
maybe use FileNotFoundError?

2022-12-20 09:16 UTC, guderkar commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
There may be different exceptions depending on existence of fs table and hive table
![image](https://user-images.githubusercontent.com/22962839/208629609-54e608a8-716d-4937-aa08-717aea5f3973.png)
![image](https://user-images.githubusercontent.com/22962839/208629624-2aeaf8f6-59ce-481b-97d6-aa8a0bacbc8b.png)

2022-12-20 09:28 UTC, ds-lukaslangr commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
we could catch the ValueError to find out that the hive table doesn't exists right?

2022-12-20 09:39 UTC, guderkar commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
Yes but it's rather confusing
```
hive not exists, feature store not exists -> ValueError
hive exists, feature store not exists  -> Exception
hive not exists, feature store exists -> ValueError
```
Also in that particular file we would be using two approaches to determine if hive table exists
- catching ValueError
- using `hive_table_exists` function

2022-12-20 09:49 UTC, guderkar commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
Or maybe we could just call fs.get_table and let the library raise the exception

2022-12-20 09:57 UTC, ds-lukaslangr commented on src/odap/feature_factory/feature_store.py
> +    except Exception:  # noqa pylint: disable=broad-except
sounds good

2023-01-17 09:53 UTC, ds-lukaslangr requested changes

2023-01-17 09:53 UTC, ds-lukaslangr commented on odap-framework-demo/_demo/_setup/init.py
> +use_cases_db = f"{env}_odap_use_cases"
this db doesnt have `{write_env}` in config.yaml

2023-01-17 09:53 UTC, ds-lukaslangr commented on odap-framework-demo/config.yaml
>      database: "{write_env}_odap_features_{entity}"
usecasefactory:
    table: "odap_use_cases.use_cases"
    
use case table doesn't support `{write_env}` formatting right now

2023-01-17 09:53 UTC, ds-lukaslangr commented on odap-framework-demo/config.yaml
> +      table: "{write_env}_odap_segments.export_logs"
is this supported in the segment factory config code?

2023-01-17 09:53 UTC, ds-lukaslangr commented on odap-package/src/odap/common/tables.py
> +    except:  # noqa pylint: disable=bare-except
can we at least use `except Exception`?

2023-01-17 10:30 UTC, guderkar commented on odap-framework-demo/config.yaml
> +      table: "{write_env}_odap_segments.export_logs"
yes
![image](https://user-images.githubusercontent.com/22962839/212875722-a541d090-2a9c-4b76-9826-a735586288d0.png)

2023-01-17 10:32 UTC, guderkar commented on odap-package/src/odap/common/tables.py
> +    except:  # noqa pylint: disable=bare-except
done

2023-01-17 10:44 UTC, guderkar commented on odap-framework-demo/_demo/_setup/init.py
> +use_cases_db = f"{env}_odap_use_cases"
fixed

2023-01-17 10:44 UTC, guderkar commented on odap-framework-demo/config.yaml
>      database: "{write_env}_odap_features_{entity}"
seems it does
![image](https://user-images.githubusercontent.com/22962839/212878887-13d8e73f-cc03-4b48-9b89-b127afa3e558.png)

2023-01-17 11:02 UTC, ds-lukaslangr approved these changes

2023-01-17 11:10 UTC, merged