✨ added lookalike functionality
DataSentics/odap pull request #59
Opened 2023-01-10 07:39 UTC by SamBajanik

2023-01-10 15:49 UTC, guderkar requested changes

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if (isinstance(value, float)):
what is the purpose if this if else? if float then fiter, if int then limit? Shouldn't we split it in two different functions?

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    return [int(date_part) for date_part in date_string.split("-")]
can't we just parse with datetime module? and return datitime object, then access like 
```
parsed_date = parse_date(date_str)
parsed_date.year/month/day
```

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    predictions_df = model.transform(features)
why we are aliasing predicted column by feature_name?

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if "probability" in predictions_df.columns:
not sure why sometimes it's probability and sometimes prediction but this code can be refactored like this
```
prediction_col = f.round(f.element_at(vector_to_array(f.col("probability")), 2).cast("float"), 3) if "probability" in predictions_df.columns else f.round("prediction", 3)

return predictions_df.select(
    dbutils.widgets.get("entity_id_column_name"),
    "timestamp",
    prediction_col.alias(feature_name),
)
```

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    how="anti",
is it left anti join? if yes write it as leftanti

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    how="semi",
leftsemi?

2023-01-10 15:49 UTC, guderkar commented on odap-framework-demo/use_cases/upsell_uc/segments/lals_cookies_highly_likely_to_submit.py
> +def return_slider(criterion):
do we need the slider here?

2023-01-11 07:44 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if (isinstance(value, float)):
it is a function that should respond to the choices of the user he makes interactively, he can choose two criterions for defining lookalikes and based on the choice, we must either use filter or limit logic, the output of the function is always the lookalike segment, therefore I decided to put it into one function

2023-01-11 07:49 UTC, SamBajanik commented on odap-framework-demo/use_cases/upsell_uc/segments/lals_cookies_highly_likely_to_submit.py
> +def return_slider(criterion):
you are right, we do not need it, i will remove it

2023-01-11 08:18 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    how="anti",
yes, left

2023-01-11 08:18 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    how="semi",
yes, left

2023-01-11 08:22 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if "probability" in predictions_df.columns:
thanks, i will replace it with this code

2023-01-11 08:24 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if "probability" in predictions_df.columns:
sometimes, the model output does not have to contain probability colum

2023-01-11 08:52 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    return [int(date_part) for date_part in date_string.split("-")]
ok, I have modified it this way

2023-01-11 08:55 UTC, guderkar requested changes

2023-01-11 08:55 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if (isinstance(value, float)):
if those functions are moved in plain .py files and imported then would it work?

2023-01-11 08:58 UTC, guderkar commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    predictions_df = model.transform(features)
but feature is kinda weird name for this variable. Shouldn't it be something like `prediction_output_col_name` with default value of `"prediction"`?

2023-01-11 08:59 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    if (isinstance(value, float)):
yes, i think so

2023-01-11 09:09 UTC, SamBajanik commented on odap-framework-demo/lookalike_modelling/explore_the_lookalike.py
> +    predictions_df = model.transform(features)
it is taken from ai features, thats it is called so, but i will rename it for this purpose, you are right

2023-01-13 08:37 UTC, guderkar approved these changes

2023-01-13 09:25 UTC, merged