:sparkles: Upgraded metadata
DataSentics/odap pull request #6
Opened 2022-10-24 06:52 UTC by Vinsho

- Changed metadata structure
- Now support templates
- Added dtype column
- Added feature and description template column

2022-10-24 07:54 UTC, guderkar requested changes

2022-10-24 07:54 UTC, guderkar commented on src/odap/feature_factory/dataframes.py
> +        feature_df = create_dataframe_from_notebook_cells(feature_path, notebook_cells[:])
what is this `[:]` think it does not have any effect

2022-10-24 07:54 UTC, guderkar commented on src/odap/feature_factory/metadata.py
> +        raise MissingFeaturesInMetadataException(f"Features section is missing in metadata for feature {feature_path}")
MissingFeaturesInMetadataException evokes that features produced by actual dataframe missing in metadata.

Wouln't be better to to create more general exception like `MetadataParsingException` for those cases?

2022-10-24 07:58 UTC, guderkar requested changes

2022-10-24 07:58 UTC, guderkar commented on src/odap/feature_factory/metadata_schema.py
> +    return feature_field.dataType.simpleString()
simpleString gives values like bigint, samllint, etc., can you please add normalization like here https://github.com/daipe-ai/feature-store-bundle/blob/f37cc3f9c69176cbc1404be27a5afddf63f984f0/src/featurestorebundle/utils/types.py#L72

2022-10-24 07:58 UTC, guderkar commented on src/odap/feature_factory/metadata.py
> +    parsed_feature[FEATURE] = feature_lines.pop(0).strip().replace("`", "")
Let's make backtics for feature mandatory

2022-10-24 07:59 UTC, guderkar requested changes

2022-10-24 07:59 UTC, guderkar commented on src/odap/feature_factory/metadata_schema.py
> +            t.StructField("category", t.StringType(), True),
Let's make constants for all metadata to be consistent

2022-10-24 08:31 UTC, Vinsho commented on src/odap/feature_factory/dataframes.py
> +        feature_df = create_dataframe_from_notebook_cells(feature_path, notebook_cells[:])
It makes copy from notebook_cells. I remove metadata cell inside `create_dataframe_from_notebook_cells` (because SQL fails with it..) But I need that metadata cell later. I'll change it and make it more clear.

2022-10-26 09:14 UTC, guderkar approved these changes

2022-10-26 09:16 UTC, merged