:sparkles: Added method for loading target features
DataSentics/odap pull request #74
Opened 2023-02-08 10:51 UTC by Vinsho

2023-02-08 13:31 UTC, ds-lukaslangr requested changes

2023-02-08 13:31 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_store.py
> +        metadata.filter(metadata.feature.isin(features) | metadata.category.isin(categories))
what if I enter a feature name or category which doesn't exist?

2023-02-08 13:36 UTC, Vinsho commented on odap-package/src/odap/feature_factory/feature_store.py
> +        metadata.filter(metadata.feature.isin(features) | metadata.category.isin(categories))
Well depends if we want to raise an exception if it doesn't exist

2023-02-08 13:38 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_store.py
> +        metadata.filter(metadata.feature.isin(features) | metadata.category.isin(categories))
I think so, this would be failing silently otherwise
I would just make a diff between the inputs and the outputs and if not empty raise an exception showing the diff

2023-02-09 12:50 UTC, Vinsho commented on odap-package/src/odap/common/dataframes.py
> +            raise Exception(f"Value {value} is not present in column {column}")
Good point! I'm thinking if I should check categories and features and print both of them in one exception if category and feature is missing. But that would be a bit of an overkill imo.

2023-02-09 13:09 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +            raise Exception(f"Value {value} is not present in column {column}")
I think it's ok to check categories first and then features

2023-02-09 13:48 UTC, ds-lukaslangr requested changes

2023-02-09 13:48 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_store.py
> +    entity_name: str, features: List[str] = [], categories: List[str] = []
`features: List[str] = [], categories: List[str] = []`
you shouldn't use `[]` as default values
it should be 
`features: List[str] = None, categories: List[str] = None`
and 
`features  = [] if features is not None else features`

2023-02-09 13:48 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +def get_values_missing_from_df_column(df: DataFrame, column: str, values: List[str]) -> List[str]:
this function is general enough that it doesn't have to take and return `List[str]`
it could use a generic type
https://stackoverflow.com/questions/6725868/generics-templates-in-python

2023-02-09 13:56 UTC, Vinsho commented on odap-package/src/odap/feature_factory/feature_store.py
> +    entity_name: str, features: List[str] = [], categories: List[str] = []
Shouldn't in case I'm changing the value of the list.

2023-02-09 14:05 UTC, Vinsho commented on odap-package/src/odap/feature_factory/feature_store.py
> +    entity_name: str, features: List[str] = [], categories: List[str] = []
I'm aware that it can be dangerous, but not really in this case because I'm not altering the list value -> I don't mind that the same instance is used every time.

2023-02-09 14:26 UTC, Vinsho commented on odap-package/src/odap/common/dataframes.py
> +def get_values_missing_from_df_column(df: DataFrame, column: str, values: List[str]) -> List[str]:
Not sure if I understand. I used `Iterable[Hashable]` and generic `List` instead.

2023-02-09 14:27 UTC, ds-lukaslangr approved these changes

2023-02-09 14:28 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +def get_values_missing_from_df_column(df: DataFrame, column: str, values: List[str]) -> List[str]:
instead of `values: List[str]) -> List[str]:` 
it can be `values: List[T]) -> List[T]:`
where `T = TypeVar('T')`

2023-02-09 14:29 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +def get_values_missing_from_df_column(df: DataFrame, column: str, values: List[str]) -> List[str]:
it's not necessary, I just thought it might be cool :)

2023-02-09 14:57 UTC, merged