add support for multi-source and for feature prefix
DataSentics/odap pull request #82
Opened 2023-09-26 10:47 UTC by corina-teodora-coste

Adding support for multi-source and for feature prefix.

2023-10-02 09:12 UTC, ds-lukaslangr requested changes

2023-10-02 09:12 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/config.py
> +def get_repository(config: Config) -> dict:
rename repositories - something like feature sources?

2023-10-02 09:12 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/orchestrate.py
> +def process_feature_dir(config: Dict, feature_dir: str, prefix: str) -> Any:
this shouldn't be here
the idea is that the write_features_df function takes the notebook mapping and calculates, this function shouldn't know anything about where the features come from or about any prefixes, it should remain the same

implement this change by getting a list of paths to all the feature notebooks across multiple folders, have the FeatureNotebook class handle the prefixing, everything else stays the same

2023-10-02 09:12 UTC, ds-lukaslangr commented on odap_framework_demo/config.yaml
> +    repositories:
this should ideally work for any number of repositories
part of the integration test should be to calculate features from at least 3 folders

also it should still test the base case of just one repo

2023-10-02 09:12 UTC, ds-lukaslangr commented on odap_framework_demo/config.yaml
>      feature_dir: "notebooks"
this config option should somehow be assimilated into the new repositories/feature sources config

2023-10-06 08:58 UTC, ds-lukaslangr requested changes

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/orchestrate.py
> +    feature_notebooks = feature_notebooks_from_dirs(config)
`feature_notebooks` should be a List of FeatureNotebook not a List of Lists
you can use list.extend() to flatten it and then all the for loop with sublists are unnecessary

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/widgets.py
> +    for repo in feature_dir:
could we get the prefix here so we can tell apart notebooks with the same name from different folders?

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/metadata.py
> +    notebook_cells: List[str], feature_path: str, feature_df: DataFrame, prefix: str = ""
prefix: str = "" is a bad practice because "" is always the same object
https://www.codecademy.com/learn/learn-intermediate-python-3/modules/int-python-function-arguments/cheatsheet

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/metadata.py
> +        if not metadata["feature"].startswith(prefix):
feature metadata should start with the prefix

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/metadata.py
> +            metadata["feature"] = f'{prefix}_{metadata["feature"]}'
this doesn't work for empty prefix
it changes all feature names to `_feature_name`

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/orchestrate.py
> +    for repo in feature_dirs:
this code is duplicated from the previous function

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/dq_checks.py
> +    feature_notebooks_list = [notebook.metadata for sublist in feature_notebooks for notebook in sublist]
this shouldn't change

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap_framework_demo/notebooks/transactions_sum_amount.sql
> --- Databricks notebook source
why is this deleted?

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        df = df_with_prefix.withColumnRenamed(f"{prefix}_{entity_primary_key}", entity_primary_key).withColumnRenamed(
why are you prefixing PK and timestamp?

2023-10-06 08:58 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +FeatureNotebookList = List[List[FeatureNotebook]]
this shouldn't change

2023-10-06 13:06 UTC, corina-teodora-coste commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +FeatureNotebookList = List[List[FeatureNotebook]]
fixed this

2023-10-06 13:14 UTC, corina-teodora-coste commented on odap_framework_demo/notebooks/transactions_sum_amount.sql
> --- Databricks notebook source
It was just for testing. I tried to read from multiple repos (3 to be exact) and I just allocated the feature notebooks randomly to each. (some had all 3 of the test features, some only 2 of them and so on).

2023-10-06 13:14 UTC, corina-teodora-coste commented on odap-package/src/odap/feature_factory/dq_checks.py
> +    feature_notebooks_list = [notebook.metadata for sublist in feature_notebooks for notebook in sublist]
this is fixed

2023-10-06 13:25 UTC, corina-teodora-coste commented on odap-package/src/odap/feature_factory/metadata.py
> +            metadata["feature"] = f'{prefix}_{metadata["feature"]}'
When testing it, it did not add it like that. I tested 3 repos .2 of them had the prefix, one didn't and I also tested when there is only one repo and it has (or not) the prefix, and it did not create the feature with the _feature_name, it just added the  default name, but I will test it again and add a condition for else so everything will be ok.  I will rethink the solution for this so it will fix all the other things you mentions :)

2023-10-09 14:08 UTC, ds-lukaslangr requested changes

2023-10-09 14:08 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +        df_with_lower_columns = df.toDF(*[f"{prefix}_{column.lower()}" for column in df.columns])
if you prefix only columns which are not **entity primary key and timestamp** then you can delete 
the `create_dataframe_with_prefix` function

2023-10-09 14:08 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +def get_prefix_for_feature(feature_path):
this function breaks the flow of the application
it should work in a way that the FeatureNotebook already gets it's prefix from the caller and doesn't have to look it up
if in `orchestrate.py` in function `feature_notebooks_from_dirs` you load the paths and prefixes from config, then you can pass them to `load_feature_notebooks` which can then pass it to FeatureNotebook.from_api and you don't have to look them up twice

2023-10-09 14:08 UTC, ds-lukaslangr commented on odap-package/src/odap/common/dataframes.py
> +    else:
if else is generally not a good practice
you can refactor this so that if prefix only handles the prefixes and the lowercasing happens every time

2023-10-09 14:08 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/dataframes/dataframe_creator.py
> +
remove newline

2023-10-09 14:08 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/dataframes/dataframe_writer.py
> +
remove newline

2023-10-09 19:51 UTC, corina-teodora-coste commented on odap-package/src/odap/common/dataframes.py
> +        df_with_lower_columns = df.toDF(*[f"{prefix}_{column.lower()}" for column in df.columns])
I integrated this in FeatureNotebook and leave create_dataframe_from_notebook_cells function unchanged. Let me know if the new approach is better.

2023-10-09 19:51 UTC, corina-teodora-coste commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +def get_prefix_for_feature(feature_path):
Fixed this.

2023-10-12 13:29 UTC, closed without merging