Feature switch-off
DataSentics/odap pull request #88
Opened 2023-11-01 23:15 UTC by hjeni

Implementation of a possibility to specify individual notebooks (within `config.yaml`) that would be included/excluded from the orchestration. 

This should stay optional (all featutre notebooks would be included if nothing was defined in the config).

2023-11-02 10:39 UTC, ds-lukaslangr requested changes

2023-11-02 10:39 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +    # not optimal for large lists - both filters have quadratic complexity
you can transform them into sets

2023-11-02 10:39 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +    notebooks_include = config.get_included_notebooks()
notebooks_to_include

2023-11-02 20:38 UTC, hjeni commented on odap-package/src/odap/feature_factory/config.py
> +            return [const.INCLUDE_NOTEBOOKS_WILDCARD, ]
No, changed to `[const.INCLUDE_NOTEBOOKS_WILDCARD]`.

2023-11-02 20:38 UTC, hjeni commented on odap-package/src/odap/feature_factory/config.py
> +            return [const.INCLUDE_NOTEBOOKS_WILDCARD, ]
No, changed to `[const.INCLUDE_NOTEBOOKS_WILDCARD]`.

2023-11-02 20:39 UTC, hjeni commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
I changed the filtering of included/excluded notebooks per data source (still working with their `basename`)

2023-11-02 20:42 UTC, hjeni commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
I changed the filtering of included/excluded notebooks per data source (still working with their `basename`). Do you still think we should make inclusions/exclusions into glob patterns on a per-source level?

2023-11-02 20:52 UTC, hjeni commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
I would definitely be safer, but naming notebooks the same shouldn't happen in the first place. If it does, all the notebooks with the matching basename would simply get excluded which is an expected behaviour.

2023-11-03 19:14 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
I think the main problem is with folders inside the path folder
you can have notebooks in path `./notebooks/digi/notebook1` and `./notebooks/customer/notebook1`
how do you include/exclude them?
do you use `- digi/notebook1` or just `- notebook1`?
would you force the user to name each notebook uniquely to allow maximum control?

2023-11-06 10:07 UTC, hjeni commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
Yea, I’d force different naming if users really want to exclude individual notebooks ATM, I don’t think you should have notebooks with the same name for different features anyway. Exclusion still works now, only that multiple notebooks with the same base name are possibly excluded from the orchestration at once.

2023-11-06 10:27 UTC, ds-lukaslangr commented on odap-package/src/odap/feature_factory/feature_notebook.py
> +        notebooks = [ntb for ntb in notebooks if ntb.info.basename in notebooks_include]
ok I'm fine with that but we have to explain this in documentation

2023-11-06 10:29 UTC, ds-lukaslangr approved these changes

2023-11-21 14:41 UTC, merged