Multiple configs
DataSentics/odap pull request #89
Opened 2023-11-03 19:32 UTC by hjeni

Adding an option to specify an environmental variable that would define a relative path (from root) to the YAML config. If not defined, the default is used.

2023-11-06 07:43 UTC, ds-lukaslangr requested changes

2023-11-06 07:43 UTC, ds-lukaslangr commented on odap-package/src/odap/common/config.py
> +    path = os.environ.get("CONFIG_PATH")
is this really PATH or is it a NAME/FILE?
also it should probably be called something like ODAP_CONFIG_FILE because it might class with other programs running on the same cluster which might use a variable called CONFIG_PATH

2023-11-06 07:43 UTC, ds-lukaslangr commented on odap-package/src/odap/common/config.py
> +def get_config_rel_path() -> str:
maybe get_config_file_name? or do we wanna support putting any relative path not just root dir?

2023-11-06 10:09 UTC, hjeni commented on odap-package/src/odap/common/config.py
> +    path = os.environ.get("CONFIG_PATH")
Good point, I’ll change the env var name.

2023-11-06 10:10 UTC, hjeni commented on odap-package/src/odap/common/config.py
> +def get_config_rel_path() -> str:
Probably not 👍

2023-11-14 16:04 UTC, ds-lukaslangr approved these changes

2023-11-21 14:42 UTC, merged